name: accounting-app
services:
- name: web
  source_dir: /
  github:
    repo: your-username/your-repo
    branch: main
  run_command: gunicorn --worker-tmp-dir /dev/shm app:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
databases:
- engine: PG
  name: accounting-db
  num_nodes: 1
  size: basic-xs
  version: "13" 