"""add dokidka and internal_transfer fields

Revision ID: 5d3cfa67f6cd
Revises: 
Create Date: 2025-07-04 04:24:30.947750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3cfa67f6cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('telegram', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initial_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.String(length=20), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('balances_json', sa.Text(), nullable=False),
    sa.Column('scam_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('scam_comment', sa.Text(), nullable=True),
    sa.Column('scam_personal', sa.Boolean(), nullable=True),
    sa.Column('dokidka_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('internal_transfer_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('dokidka_comment', sa.Text(), nullable=True),
    sa.Column('internal_transfer_comment', sa.Text(), nullable=True),
    sa.Column('bybit_file', sa.String(length=255), nullable=True),
    sa.Column('htx_file', sa.String(length=255), nullable=True),
    sa.Column('bliss_file', sa.String(length=255), nullable=True),
    sa.Column('start_photo', sa.String(length=255), nullable=True),
    sa.Column('end_photo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('bybit_requests', sa.Integer(), nullable=True),
    sa.Column('htx_requests', sa.Integer(), nullable=True),
    sa.Column('bliss_requests', sa.Integer(), nullable=True),
    sa.Column('bybit_first_trade', sa.String(length=100), nullable=True),
    sa.Column('bybit_last_trade', sa.String(length=100), nullable=True),
    sa.Column('htx_first_trade', sa.String(length=100), nullable=True),
    sa.Column('htx_last_trade', sa.String(length=100), nullable=True),
    sa.Column('bliss_first_trade', sa.String(length=100), nullable=True),
    sa.Column('bliss_last_trade', sa.String(length=100), nullable=True),
    sa.Column('gate_first_trade', sa.String(length=100), nullable=True),
    sa.Column('gate_last_trade', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_report_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('total_usdt', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fees_usdt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shift_report_id'], ['shift_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_detail')
    op.drop_table('shift_report')
    op.drop_table('account')
    op.drop_table('initial_balance')
    op.drop_table('employee')
    # ### end Alembic commands ###
