"""add salary settings table

Revision ID: 7f4c8d9e1a23
Revises: 6ea14ce19836
Create Date: 2024-07-11 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4c8d9e1a23'
down_revision = '6ea14ce19836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('base_percent', sa.Integer(), nullable=False, server_default='30'),
        sa.Column('min_requests_per_day', sa.Integer(), nullable=False, server_default='50'),
        sa.Column('bonus_percent', sa.Integer(), nullable=False, server_default='5'),
        sa.Column('bonus_requests_threshold', sa.Integer(), nullable=False, server_default='70'),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_settings')
    # ### end Alembic commands ### 