"""add salary_percent to employee

Revision ID: daae5e05aa18
Revises: 3f3c76caa924
Create Date: 2025-07-04 19:50:25.582706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daae5e05aa18'
down_revision: Union[str, Sequence[str], None] = '3f3c76caa924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('salary_percent', sa.Numeric(precision=5, scale=2), nullable=False))
    op.alter_column('employee', 'telegram',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'telegram',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('employee', 'salary_percent')
    # ### end Alembic commands ###
